FROM node:26-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG PUBLIC_API_URL=http://backend:8000
RUN npm run build

FROM mcr.microsoft.com/playwright:v1.60.0-noble
WORKDIR /app
COPY --from=builder /app ./app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/playwright.config.ts ./
COPY --from=builder /app/tests ./tests
CMD ["npx", "playwright", "test"]
