// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Body_login-login_access_token
 */
export const zBodyLoginLoginAccessToken = z.object({
    grant_type: z.string().regex(/^password$/).nullish(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.string().nullish(),
    client_secret: z.string().nullish()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish()
});

/**
 * ItemPublic
 */
export const zItemPublic = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish(),
    id: z.uuid(),
    owner_id: z.uuid(),
    created_at: z.iso.datetime().nullish()
});

/**
 * ItemUpdate
 */
export const zItemUpdate = z.object({
    title: z.string().min(1).max(255).nullish(),
    description: z.string().max(255).nullish()
});

/**
 * ItemsPublic
 */
export const zItemsPublic = z.object({
    data: z.array(zItemPublic),
    count: z.int()
});

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * NewPassword
 */
export const zNewPassword = z.object({
    token: z.string(),
    new_password: z.string().min(8).max(128)
});

/**
 * PrivateUserCreate
 */
export const zPrivateUserCreate = z.object({
    email: z.string(),
    password: z.string(),
    full_name: z.string(),
    is_verified: z.boolean().optional().default(false)
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

/**
 * UpdatePassword
 */
export const zUpdatePassword = z.object({
    current_password: z.string().min(8).max(128),
    new_password: z.string().min(8).max(128)
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    email: z.email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime().nullish()
});

/**
 * UserRegister
 */
export const zUserRegister = z.object({
    email: z.email().max(255),
    password: z.string().min(8).max(128),
    full_name: z.string().max(255).nullish()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    email: z.email().max(255).nullish(),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128).nullish()
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    full_name: z.string().max(255).nullish(),
    email: z.email().max(255).nullish()
});

/**
 * UsersPublic
 */
export const zUsersPublic = z.object({
    data: z.array(zUserPublic),
    count: z.int()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zLoginLoginAccessTokenBody = zBodyLoginLoginAccessToken;

/**
 * Successful Response
 */
export const zLoginLoginAccessTokenResponse = zToken;

/**
 * Successful Response
 */
export const zLoginTestTokenResponse = zUserPublic;

export const zLoginRecoverPasswordPath = z.object({
    email: z.string()
});

/**
 * Successful Response
 */
export const zLoginRecoverPasswordResponse = zMessage;

export const zLoginResetPasswordBody = zNewPassword;

/**
 * Successful Response
 */
export const zLoginResetPasswordResponse = zMessage;

export const zLoginRecoverPasswordHtmlContentPath = z.object({
    email: z.string()
});

/**
 * Successful Response
 */
export const zLoginRecoverPasswordHtmlContentResponse = z.string();

export const zUsersReadUsersQuery = z.object({
    skip: z.int().optional().default(0),
    limit: z.int().optional().default(100)
});

/**
 * Successful Response
 */
export const zUsersReadUsersResponse = zUsersPublic;

export const zUsersCreateUserBody = zUserCreate;

/**
 * Successful Response
 */
export const zUsersCreateUserResponse = zUserPublic;

/**
 * Successful Response
 */
export const zUsersDeleteUserMeResponse = zMessage;

/**
 * Successful Response
 */
export const zUsersReadUserMeResponse = zUserPublic;

export const zUsersUpdateUserMeBody = zUserUpdateMe;

/**
 * Successful Response
 */
export const zUsersUpdateUserMeResponse = zUserPublic;

export const zUsersUpdatePasswordMeBody = zUpdatePassword;

/**
 * Successful Response
 */
export const zUsersUpdatePasswordMeResponse = zMessage;

export const zUsersRegisterUserBody = zUserRegister;

/**
 * Successful Response
 */
export const zUsersRegisterUserResponse = zUserPublic;

export const zUsersDeleteUserPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zMessage;

export const zUsersReadUserByIdPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUsersReadUserByIdResponse = zUserPublic;

export const zUsersUpdateUserBody = zUserUpdate;

export const zUsersUpdateUserPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserPublic;

export const zUtilsTestEmailQuery = z.object({
    email_to: z.email()
});

/**
 * Successful Response
 */
export const zUtilsTestEmailResponse = zMessage;

/**
 * Response Utils-Health Check
 *
 * Successful Response
 */
export const zUtilsHealthCheckResponse = z.boolean();

export const zItemsReadItemsQuery = z.object({
    skip: z.int().optional().default(0),
    limit: z.int().optional().default(100)
});

/**
 * Successful Response
 */
export const zItemsReadItemsResponse = zItemsPublic;

export const zItemsCreateItemBody = zItemCreate;

/**
 * Successful Response
 */
export const zItemsCreateItemResponse = zItemPublic;

export const zItemsDeleteItemPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zItemsDeleteItemResponse = zMessage;

export const zItemsReadItemPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zItemsReadItemResponse = zItemPublic;

export const zItemsUpdateItemBody = zItemUpdate;

export const zItemsUpdateItemPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zItemsUpdateItemResponse = zItemPublic;

export const zPrivateCreateUserBody = zPrivateUserCreate;

/**
 * Successful Response
 */
export const zPrivateCreateUserResponse = zUserPublic;
